name: CI

on: push

jobs:
  ruby-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        entry:
          - name: Minimum Rails
            ruby: '2.7'
            gemfile: Gemfile.rails-min
          - name: Latest Rails
            ruby: '3.2'
            gemfile: Gemfile.rails-latest
          - name: Edge Rails
            ruby: '3.2'
            gemfile: "Gemfile.rails-edge"

    name: ${{ matrix.entry.name }}
    env:
      BUNDLE_GEMFILE: gemfiles/${{ matrix.entry.gemfile }}
    steps:
      - uses: actions/checkout@v3
        name: Checkout

      - uses: ruby/setup-ruby@v1
        name: Use Ruby ${{ matrix.entry.ruby }}
        with:
          ruby-version: ${{ matrix.entry.ruby }}
          bundler-cache: true

      - name: 💅🏼 Lint
        run: bundle exec rubocop --fail-fast

      - name: Test
        run: bundle exec rake spec
