name: CI

on: push

jobs:
  ruby-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby-version: [2.6, 2.7, 3.0]

    steps:
      - uses: actions/checkout@v2
        name: Checkout

      - uses: ruby/setup-ruby@v1
        name: Use Ruby ${{ matrix.ruby-version }}
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - name: 💅🏼 Lint
        run: bundle exec rubocop --fail-fast

      - name: Test
        run: bundle exec rake test
